### ISSUE TITLE
Can't install using upip - ESP8266

### ISSUE THREAD

**Issue by thalesmaoa** [brainelectronics/micropython-modbus#71]
### Description

I'm following the docs in a new esp8266 chip. I'm getting error.

### Reproduction steps

```python
>>> upip.install('micropython-modbus')
Installing to: /lib/
Error installing 'micropython-modbus': , packages may be partially installed
```

### MicroPython version

v1.19.1

### MicroPython board

ESP8266

### MicroPython Modbus version

```python
>>> import os
>>> from umodbus import version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'umodbus'
>>> print('MicroPython infos:', os.uname())
MicroPython infos: (sysname='esp8266', nodename='esp8266', release='2.2.0-dev(9422289)', version='v1.19.1 on 2022-06-18', machine='ESP module with ESP8266')
>>> print('Used micropthon-modbus version:', version.__version__))
Traceback (most recent call last):
  File "<stdin>", line 1
SyntaxError: invalid syntax
```

**Comment by thalesmaoa** [comment]
This happens due to a lack of memory. Should by frozen within micropython
